spring:
  application:
    name: eprescription-out-of-stock

  datasource:
    url: jdbc:mysql://localhost:3306/eprescription-out-of-stock
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  app:
    jwtSecret: abcdefghijKLMNOPQRSTUvwxyz=====LEMOBILE====0123456987
    jwtExpirationMs:  21600000
    refreshExpirationMs: 18000000


file:
  dir-attachments:  /home/yemane/Documents/Medco/lemobile/attachments


afromessage:
  api:
    url: "https://api.afromessage.com/api/send"
    token: eyJhbGciOiJIUzI1NiJ9.eyJpZGVudGlmaWVyIjoiYkpUZ1VZVzJoaTZnaFo5QTJDSjBaU3pzeWhLZ2ZtVWsiLCJleHAiOjE4OTM0NzkxNjUsImlhdCI6MTczNTcxMjc2NSwianRpIjoiMmVlMGNmOWUtOGFlMC00NDQ0LWFjY2UtODdhNjU0MjhiNmQxIn0.D5_eQNtA4HNaNuVo1O6pydwaZ-sn3fpWZa-g4rjl1IU
    identifierId: e80ad9d8-adf3-463f-80f4-7c4b39f7f164
kenema:
  api:
    url: "http://localhost:8800/api/v1/reports"



servlet:
  multipart:
    enabled: true
    max-file-size: 100MB
    max-request-size: 120MB
    file-size-threshold: 2MB
    resolve-lazily: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: 8400
